# Challenge - Joining on multiple tables

# 1. List the number of films per category.

SELECT name, (COUNT(film_id))
FROM category
INNER JOIN film_category
ON category.category_id = film_category.category_id
GROUP BY name;

# 2. Retrieve the store ID, city, and country for each store

SELECT store_ID, city.city, country.country
FROM store
INNER JOIN address
ON store.address_ID = address.address_ID
INNER JOIN city
ON address.city_id = city.city_id
INNER JOIN country
ON city.country_id = country.country_id;

# 3. Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, SUM(p.amount)
FROM store AS s
INNER JOIN staff AS st ON s.store_id = st.store_id
INNER JOIN payment AS p ON st.staff_id = p.staff_id
GROUP BY s.store_id;

# 4. Determine the average running time of films for each category

SELECT c.name, AVG(f.length)
FROM film AS f
INNER JOIN film_category AS fc 
    ON f.film_id = fc.film_id
INNER JOIN category AS c 
    ON c.category_id = fc.category_id
GROUP BY c.name;

# 5. Identify the film categories with the longest average running time.
SELECT c.name, AVG(f.length)
FROM film AS f
INNER JOIN film_category AS fc 
    ON f.film_id = fc.film_id
INNER JOIN category AS c 
    ON c.category_id = fc.category_id
GROUP BY c.name 
ORDER BY AVG(f.length) DESC;

# 6 Display the top 10 most frequently rented movies in descending order.

SELECT f.title, COUNT(r.rental_id)
FROM film AS f
INNER JOIN inventory AS i ON f.film_id = i.film_id
INNER JOIN rental AS r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY COUNT(r.rental_id) DESC 
LIMIT 10;

# 7 Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT title
FROM film
INNER JOIN inventory ON film.film_id = inventory.film_id
WHERE title =  'Academy Dinosaur' AND store_id = 1;


